# Generated by Django 5.0.3 on 2024-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('p_type', models.CharField(max_length=200)),
            ],
        ),
    ]
