version: '3.0'

services:
  python:
    build:
      context: .
      target: backend
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - redis
    
  redis:
    image: redis
    ports:
      - 6379:6379


    