version: '3.0'

services:
  python:
    build:
      context: .
      target: backend
    ports:
      - 8000:8000
    volumes:
      - .:/testtask
    depends_on:
      - redis
  
  celery_worker:
    build: .
    volumes:
      - .:/testtask
    command: celery -A testtask worker -l info
    depends_on:
      - redis
      - python
    

  celery_beat:
    build: .
    volumes:
      - .:/testtask
    command: celery -A testtask beat -l INFO
    depends_on:
      - python
      - redis
    

  redis:
    image: redis
