version: '3.0'

services:
  python:
    build:
      context: .
      target: backend
    ports:
      - 8000:8000
    volumes:
      - .:/testtask
    depends_on:
      - redis
      - db
      - migrate

  migrate:
    build: .
    volumes:
      - .:/testtask
    command: python manage.py migrate
    depends_on:
      - redis
      - db
  
  celery_worker:
    build: .
    volumes:
      - .:/testtask
    command: celery -A testtask worker -l info
    depends_on:
      - redis
      - migrate
      - python
    

  celery_beat:
    build: .
    volumes:
      - .:/testtask
    command: celery -A testtask beat -l INFO
    depends_on:
      - python
      - redis
      - migrate
    

  redis:
    image: redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: